import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { format } from "date-fns"
import { formatCurrency } from "../../utils/formatters.js"
import useThemeColor from "../../hooks/useThemeColor.js"

export default function PriceLineChart({ data = [], color: colorProp, height = 260 }) {
  const { accent } = useThemeColor()
  const color = colorProp && colorProp !== "#00D4FF" ? colorProp : accent
  const chartData = data.map((point) => ({ timestamp: point.timestamp || point.time || point.date, price: Number(point.price ?? point.close ?? point.current_price) })).filter((point) => Number.isFinite(point.price))
  if (!chartData.length) return <div className="h-full flex items-center justify-center font-mono text-sm text-slate-500">No price history available</div>
  return <ResponsiveContainer width="100%" height={height}><AreaChart data={chartData} margin={{ top: 14, right: 13, left: 8, bottom: 2 }}><defs><linearGradient id="price-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={0.44} /><stop offset="72%" stopColor={color} stopOpacity={0.09} /><stop offset="100%" stopColor={color} stopOpacity={0} /></linearGradient><filter id="price-glow" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation="3" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs><CartesianGrid vertical={false} stroke="currentColor" strokeOpacity={0.13} strokeDasharray="2 5" /><XAxis dataKey="timestamp" axisLine={false} tickLine={false} minTickGap={36} tick={{ fill: "currentColor", fillOpacity: .55, fontSize: 10, fontFamily: "DM Mono, monospace" }} tickFormatter={(value) => value ? format(new Date(value), "MMM d") : ""} /><YAxis width={68} axisLine={false} tickLine={false} tick={{ fill: "currentColor", fillOpacity: .55, fontSize: 10, fontFamily: "DM Mono, monospace" }} tickFormatter={(value) => formatCurrency(value)} domain={["dataMin", "dataMax"]} /><Tooltip cursor={{ stroke: color, strokeOpacity: .38, strokeWidth: 1 }} contentStyle={{ background: "rgba(4, 18, 35, .94)", border: `1px solid ${color}55`, borderRadius: 8, fontFamily: "DM Mono, monospace", fontSize: 11, boxShadow: `0 0 22px ${color}24` }} labelStyle={{ color: "#9fb5cb", marginBottom: 5 }} labelFormatter={(value) => value ? format(new Date(value), "MMM d, HH:mm") : "Latest"} formatter={(value) => [formatCurrency(value), "BTC / USD"]} /><Area type="monotone" dataKey="price" stroke={color} strokeWidth={2.25} fill="url(#price-area)" filter="url(#price-glow)" activeDot={{ r: 4, fill: color, stroke: "#fff", strokeWidth: 1.5 }} /></AreaChart></ResponsiveContainer>
}