import { useMemo, useState } from "react"
import { Search } from "lucide-react"
import { formatCompactNumber, formatCurrency, formatPercentage } from "../../utils/formatters.js"
import SkeletonLoader from "./SkeletonLoader.jsx"
const columns = [["symbol", "Asset"], ["current_price", "Price"], ["change_24h_pct", "24h"], ["volume_24h", "Volume"], ["market_cap", "Market cap"]]
export default function CryptoTable({ data = [], isLoading = false }) {
  const [search, setSearch] = useState(""); const [sort, setSort] = useState({ key: "market_cap", direction: "desc" })
  const rows = useMemo(() => data.filter((asset) => `${asset.name || ""} ${asset.symbol || ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => { const result = typeof a[sort.key] === "string" ? String(a[sort.key]).localeCompare(String(b[sort.key])) : (Number(a[sort.key]) || 0) - (Number(b[sort.key]) || 0); return sort.direction === "asc" ? result : -result }), [data, search, sort])
  const toggleSort = (key) => setSort((current) => ({ key, direction: current.key === key && current.direction === "desc" ? "asc" : "desc" }))
  if (isLoading) return <SkeletonLoader className="h-11" count={6} />
  return <div className="min-w-[620px]"><label className="relative mb-3 block"><Search size={13} className="absolute left-2.5 top-2 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter assets" className="w-full rounded-md border border-white/10 bg-navy-900/70 py-1.5 pl-7 pr-2 font-mono text-[11px] text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-400/50" /></label><table className="w-full border-collapse text-left font-mono text-[11px]"><thead className="sticky top-0 bg-navy-800 text-slate-500"><tr>{columns.map(([key, label]) => <th key={key} onClick={() => toggleSort(key)} className="cursor-pointer px-2 py-2 font-medium hover:text-cyan-300">{label}{sort.key === key ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</th>)}</tr></thead><tbody>{rows.map((asset) => { const positive = (asset.change_24h_pct || 0) >= 0; return <tr key={asset.symbol} className="border-t border-white/[0.045] text-slate-300 transition-colors hover:bg-cyan-300/[0.045]"><td className="px-2 py-2"><strong className="text-white">{asset.symbol}</strong><span className="ml-1.5 text-slate-600">{asset.cluster_label || ""}</span></td><td className="px-2 py-2 text-white">{formatCurrency(asset.current_price)}</td><td className={`px-2 py-2 ${positive ? "text-emerald-400" : "text-rose-400"}`}>{formatPercentage(asset.change_24h_pct)}</td><td className="px-2 py-2">${formatCompactNumber(asset.volume_24h)}</td><td className="px-2 py-2">${formatCompactNumber(asset.market_cap)}</td></tr> })}</tbody></table>{!rows.length && <p className="py-8 text-center text-slate-600">No matching assets</p>}</div>
}
